export default function PrivacyPage() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-16 text-slate-700">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
      <p className="text-sm text-slate-400 mb-10">Last updated: September 2026</p>

      <section className="space-y-8 text-sm leading-relaxed">
        <div>
          <h2 className="font-semibold text-slate-900 mb-2">What we collect</h2>
          <p>FollowThrough collects your email address (for login) and, if you connect Gmail, read-only access to your Gmail thread metadata (subject lines and sender names). We never read email body content.</p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900 mb-2">How we use it</h2>
          <p>Gmail data is used solely to detect open follow-up loops on your behalf using AI. No data is sold or shared with third parties. Drafts generated by AI are never sent without your explicit approval.</p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900 mb-2">Data storage</h2>
          <p>Your data is stored in Supabase (EU/US regions) and processed using Google Gemini AI. OAuth tokens are encrypted at rest. You can disconnect Gmail at any time from the app settings.</p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900 mb-2">Your rights</h2>
          <p>You can request deletion of all your data at any time by emailing us. We will process the request within 30 days.</p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900 mb-2">Contact</h2>
          <p>Questions? Email <a href="mailto:ritesh@dharanova.com" className="text-[#1a1a1a] underline underline-offset-2">ritesh@dharanova.com</a></p>
        </div>
      </section>
    </main>
  )
}
